version: "3.8"

services:
  frontend:
    build:
      context: ./apps/fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/fe:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./apps/be
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./apps/be:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

networks:
  default:
    driver: bridge
