version: "3.8"

services:
  frontend:
    build:
      context: ./apps/fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/fe:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - default

  backend:
    build:
      context: ./apps/be
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./apps/be:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    depends_on:
      - cache
    networks:
      - default

  cache:
    # TODO: Pin a specific version of Redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - default

networks:
  default:
    driver: bridge
